---
deployment:
  tasks:
    - export DEPLOYPATH=/home/doctorcu/landing.doctorcusco.com
    - /bin/mkdir -p "$DEPLOYPATH"
    - /bin/ls -la dist || true
    - /usr/bin/rsync -ah --delete dist/ "$DEPLOYPATH"/